#-----------------------------------------------------------------------------------------------------------------------
# .github/workflows/linux-ubuntu.yml is part of Brewken, and is copyright the following authors 2021-2022:
#   • Artem Martynov <martynov-a@polyplastic.by>
#   • Chris Speck <cgspeck@gmail.com>
#   • Mattias Måhl <mattias@kejsarsten.com>
#   • Matt Young <mfsy@yahoo.com>
#   • Mik Firestone <mikfire@gmail.com>
#
# Brewken is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Brewken is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#-----------------------------------------------------------------------------------------------------------------------
name: Linux

on:
  push:
    branches:
      - develop
      - "stable/**"
  pull_request:
    branches:
      - develop
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # See https://github.com/Brewken/brewken/wiki/Development:-Getting-Started for more on what is needed to build
      # the software.  It seems we can assume the following packages are already installed:
      #    cmake
      #    git
      #    debhelper
      #    rpm
      - name: Install Frameworks and Libraries
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y \
            libqt5multimedia5-plugins \
            libqt5sql5-psql \
            libqt5sql5-sqlite \
            libqt5svg5-dev \
            libxalan-c-dev \
            libxerces-c-dev \
            lintian \
            qtbase5-dev \
            qtmultimedia5-dev \
            qttools5-dev \
            qttools5-dev-tools \
            rpmlint
          cd ~
          mkdir ~/boost-tmp
          cd ~/boost-tmp
          wget https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.bz2
          tar --bzip2 -xf boost_1_79_0.tar.bz2
          cd boost_1_79_0
          ./bootstrap.sh --prefix=/usr
          sudo ./b2 install
          cd ~
          sudo rm -rf ~/boost-tmp

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          umask 022
          cmake \
            DESTDIR=/usr \
            -DDO_RELEASE_BUILD=ON \
            -DNO_MESSING_WITH_FLAGS=ON \
            $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: |
          pwd
          find ../third-party
          make

      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        env:
          CTEST_OUTPUT_ON_FAILURE: TRUE
          QT_QPA_PLATFORM: minimal
        run: |
          make test

      - name: Package
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: |
          umask 022
          make package

      - name: LintianAndRpmLint
        continue-on-error: true
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: make package_lint

      - name: Upload Linux Packages (Installers)
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: brewken-${{matrix.os}}
          path: |
            build/brewken*.rpm
            build/brewken*.rpm.sha256
            build/brewken*.deb
            build/brewken*.deb.sha256
            build/brewken*.tar.bz2
            build/brewken*.tar.bz2.sha256
          retention-days: 7

      - name: Recover Debris Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: build-results-${{matrix.os}}
          path: build
          retention-days: 1
